// <auto-generated />
namespace NewsSite_v1._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Email2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Email2));
        
        string IMigrationMetadata.Id
        {
            get { return "201709200003437_Email2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
