// <auto-generated />
namespace NewsSite_v1._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class email5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(email5));
        
        string IMigrationMetadata.Id
        {
            get { return "201709211315539_email5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
